name: Node.js CI

on:
  workflow_dispatch:

  pull_request:
    branches: [main]
    paths:
      - '**.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/*.yml'

  push:
    branches: [main]
    paths:
      - '**.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  NPM_VERSION: 20.10.0
  PNPM_VERSION: 10.2.1

jobs:
  ci:
    name: Node.js CI
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup PNPM
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NPM_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run build
        run: pnpm build

      - name: Run test
        run: pnpm test
