name: Node.js CI

on:
  workflow_dispatch:

  pull_request:
    branches: [main]
    paths:
      - '**.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/*.yml'

  push:
    branches: [main]
    paths:
      - '**.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  NPM_VERSION: 20.10.0
  PNPM_VERSION: 10.2.1

jobs:
  ci:
    name: Node.js CI
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PNPM
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.NPM_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run build
        run: pnpm build

      - name: Run test
        run: pnpm test
